<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="wheel" params="side x y z">
        <link name='wheel_${side}'>
            <visual name='wheel_${side}_visual'>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_diameter/2}" />
                </geometry>
                <material name="yellow" />
            </visual>

            <inertial>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <mass value="4" />
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.2" />
            </inertial>

            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_diameter/2}" />
                </geometry>
            </collision>
        </link>
        <joint name="wheel_${side}_joint" type="continuous">
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
            <child link="wheel_${side}" />
            <parent link="base_link" />
        </joint>

        <transmission name="tran_${side}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="wheel_${side}_joint">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="motor_${side}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>


</robot>